#runtime: python39
#env_variables:  
#  GEMINI_API_KEY: your_gemini_api_key_here
#handlers:
#  - url: /.*
#      script: auto
      

# The app.yaml file is used to configure settings for Google App Engine (GAE) applications.
